### ISSUE TITLE
Should abbreviations page include links or SW package names

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw-eb-docs2#2]
I happened to be browsing our [abbreviations](https://github.com/betterscientificsoftware/bssw-eb-docs2/blob/master/TmpFiles/Abbreviations.md) and was wondering two things...

1. Shouldn't we include links to the items cited
1. Should we include software package names? If so, maybe they should be in a separate SW list package name list

**Comment by curfman** [comment]
Actually we likely can remove this page; it was used previously to ensure correct caps for these items on the frontend, but that should no longer be needed due to an update in frontend functionality.

**Comment by markcmiller86** [comment]
Yeah, @rinkug just mentioned this in today's call.
